server:
  port: 8081

dubbo:
  protocol:
    name: dubbo
    port: -1
    host: 10.8.1.140
  service:
    version: 1.0.0
  registry:
    address: zookeeper://10.8.4.190:2181?timeout=10000
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  scan:
    base-packages: well.service
spring:
  application:
    name: copy-boot
